import re
from pathlib import Path

import pandas as pd


COLUMNS = [
    "Makale Adı & Yıl",
    "Yazar(lar)",
    "Dergi/Konferans",
    "Amaç & Katkı",
    "Kullanılan Algoritmalar/Yöntemler",
    "Bilinmesi Gereken Anahtar Kelimeler",
    "Veri Seti(leri)",
    "Yenilik / Ne Sunuyor?",
    "Karşılaştırma Yöntemleri",
    "Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.)",
    "Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi",
    "Cold Start ele alınmış mı?",
]


def _clean(value: str | None) -> str:
    if not value:
        return ""
    value = re.sub(r"\s+", " ", value).strip()
    return value


FIELD_PATTERNS: list[tuple[str, str]] = [
    ("Makale Adı & Yıl", r"Makale Adı\s*&\s*Yıl:\s*"),
    ("Yazar(lar)", r"Yazar\(lar\):\s*"),
    ("Dergi/Konferans", r"Dergi/Konferans:\s*"),
    ("Amaç & Katkı", r"Amaç\s*&\s*Katkı:\s*"),
    ("Kullanılan Algoritmalar/Yöntemler", r"Kullanılan Algoritmalar/Yöntemler:\s*"),
    ("Bilinmesi Gereken Anahtar Kelimeler", r"Bilinmesi Gereken Anahtar Kelimeler:\s*"),
    ("Veri Seti(leri)", r"Veri Seti\(leri\):\s*"),
    ("Yenilik / Ne Sunuyor?", r"Yenilik\s*/\s*Ne Sunuyor\?:\s*"),
    ("Karşılaştırma Yöntemleri", r"Karşılaştırma Yöntemleri:\s*"),
    (
        "Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.)",
        r"Performans Metrikleri ve Sonuçlar \(MAE, RMSE vb\.\):\s*",
    ),
    (
        "Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi",
        r"Kendi hibrit MF \+ Metaheuristic çalışmamla ilişkisi:\s*",
    ),
    ("Cold Start ele alınmış mı?", r"Cold Start ele alınmış mı\?:\s*"),
]


def parse_block(block: str) -> dict[str, str]:
    out: dict[str, str] = {c: "" for c in COLUMNS}

    # Normalize separators a bit (the input uses numbered citations like "1," etc.)
    text = re.sub(r"\s+", " ", block).strip()

    # Build a combined regex that can capture each field until the next field begins.
    for idx, (col, start_pat) in enumerate(FIELD_PATTERNS):
        # Lookahead for any of the next field starters or end of block.
        next_starters = [p for _, p in FIELD_PATTERNS[idx + 1 :]]
        if next_starters:
            end_pat = r"(?=(" + "|".join(next_starters) + r"))"
        else:
            end_pat = r"$"

        m = re.search(start_pat + r"(.*?)" + end_pat, text, flags=re.IGNORECASE)
        out[col] = _clean(m.group(1) if m else "")

    return out


def split_articles(raw: str) -> list[tuple[int, str]]:
    # Split on "Makale <n>" but keep the number.
    # Avoid word-boundary quirks on Windows codepages; keep it simple.
    # The source sometimes has no whitespace: "Makale 1Makale Adı..."
    # Also avoid matching the explanatory "makale1" mention by requiring "Makale Adı" next.
    parts = re.split(r"Makale\s*(\d+)(?=Makale Adı)", raw, flags=re.IGNORECASE)
    # parts = [prefix, n1, block1, n2, block2, ...]
    articles: list[tuple[int, str]] = []
    for i in range(1, len(parts), 2):
        try:
            n = int(parts[i])
        except ValueError:
            continue
        block = parts[i + 1].strip()
        if block:
            articles.append((n, block))
    return articles


RAW_TEXT = r"""
dökümanlara bir excel oluşturabilir misin? şu sütun isimleri olacak 
Makale Adı & Yıl
Yazar(lar)
Dergi/Konferans
Amaç & Katkı
Kullanılan Algoritmalar/Yöntemler
Bilinmesi Gereken Anahtar Kelimeler
Veri Seti(leri)
Yenilik / Ne Sunuyor?
Karşılaştırma Yöntemleri
Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.)
Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi
Cold Start ele alınmış mı?
sana veriyi atıcam ama ayrılmamış şekilde onları her satıra yazacaksın makale1 1.satırı temsil edecek mesela

Makale 1Makale Adı & Yıl: A Movie Recommender System Based on User Profile and Artificial Bee Colony Optimization (2023) 1, 2.Yazar(lar): Faezeh Rajabi Kouchi, Sahar Oftadeh Balani, Amirhossein Esmaeilpour, Masoume Shafieian, Rzgar Sirwan, Adil Hussein Mohammed 1.Dergi/Konferans: Computational Intelligence and Neuroscience 1.Amaç & Katkı: Kullanıcı davranışlarını matematiksel modellerle verimli şekilde modelleyerek ve öneri üretirken gereksiz bilgileri engelleyerek sistem kalitesini artırmak 3.Kullanılan Algoritmalar/Yöntemler: Yapay Arı Kolonisi (Artificial Bee Colony - ABC) Optimizasyonu ve Pearson Korelasyonu 1, 4.Bilinmesi Gereken Anahtar Kelimeler: Recommender Systems, Artificial Bee Colony, User Profile, Optimization, Pearson Correlation 1, 4, 5.Veri Seti(leri): MovieLens 1M veri seti 6.Yenilik / Ne Sunuyor?: Kullanıcı özelliklerini çıkarırken ve profilleri kümeleyip sınıflandırırken veri gürültüsünü filtrelemek için doğrudan bir meta-sezgisel algoritma (ABC) kullanır 3, 5.Karşılaştırma Yöntemleri: Sun vd. (Sun et al.) ve Yadav vd. (Yadav et al.) tarafından sunulan temel modeller ile karşılaştırılmıştır 7.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Kesinlik (Precision) ve Duyarlılık (Recall) kullanılmış; öneri sayısı ve kullanıcı hacmi arttıkça öneri kesinliğinin diğer yöntemleri geride bıraktığı görülmüştür 7, 8.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Kuracağınız MF modelinin ön işleme, özellik optimizasyonu veya benzerlik matrisi hesaplama aşamasına bir meta-sezgisel algoritmanın (ABC) nasıl entegre edilebileceği açısından doğrudan bir mimari örnektir 5, 9.Cold Start ele alınmış mı?: Sistem kullanıcıların geçmiş davranış geçmişine (behavioral information) ve seyrekliği azaltmaya odaklansa da doğrudan "Cold Start" problemine değinilmemiştir 3.
Makale 2Makale Adı & Yıl: Multi-criteria recommendation system based on deep matrix factorization and regression techniques (2024) 10.Yazar(lar): Reetu Singh, Pragya Dwivedi, Pankaj Patidar 10.Dergi/Konferans: International Journal of Information Technology 10.Amaç & Katkı: Tek bir genel puanlama kullanmak yerine, film önermede doğruluğu artırmak için farklı özelliklerin bir arada incelendiği çok kriterli (multi-criteria) bir yaklaşım sağlamak 11, 12.Kullanılan Algoritmalar/Yöntemler: Deep Matrix Factorization (Derin MF), Singular Value Decomposition (SVD), Lineer Regresyon, Lasso Regresyonu 11, 13.Bilinmesi Gereken Anahtar Kelimeler: Multi-criteria recommender system, Deep Matrix Factorization, Regression, SVD 10, 13.Veri Seti(leri): Filmlere ait; Birincil Başlık, Yönetmenler, Yazarlar ve Tür gibi kriterlere sahip film/kullanıcı veri setleri 11.Yenilik / Ne Sunuyor?: Geleneksel matris çarpanlarına ayırmayı derin öğrenme (DeepMF) ile genişletir ve birden fazla kriterin değerlendirilmesini regresyon algoritmaları üzerinden birleştirir 11, 13.Karşılaştırma Yöntemleri: Temel SVD, Autoencoder yapıları ve klasik makine öğrenimi tabanlı (PCA vb.) öneri sistemleri 13, 14.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Modeller MAE (Ortalama Mutlak Hata) ve RMSE metrikleri ile test edilmiş, hata payı diğer yaklaşımlara kıyasla önemli ölçüde düşürülmüştür 13.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Tasarladığınız Matris Çarpanlarına Ayırma (MF) altyapısının farklı veri boyutlarıyla (yönetmen, tür vb.) matrislere nasıl bölüneceğini gösterir; meta-sezgisel kısmını bu derin MF yapısına entegre edebilirsiniz 13, 15.Cold Start ele alınmış mı?: Evet (kısmen); geleneksel algoritmaların aksine Autoencoder/Derin MF bileşenlerinin seyrek veriyi (sparsity) daha iyi öğrenmesi sayesinde cold start ve veri zayıflığı sorununu hafiflettiği vurgulanmıştır 12, 14.
Makale 3Makale Adı & Yıl: Applying particle swarm optimization algorithm-based collaborative filtering recommender system considering rating and review (2023) 16.Yazar(lar): R.J. Kuo, Shu-Syun Li 16.Dergi/Konferans: Applied Soft Computing 16.Amaç & Katkı: Veri seyrekliğinin (sparsity) öneri sistemlerindeki etkisini kırmak adına sadece puanlamaları değil, kullanıcı metin yorumlarını (review) da analize dahil etmek 17.Kullanılan Algoritmalar/Yöntemler: Parçacık Sürü Optimizasyonu (PSO), Genetik Algoritma (GA), Sine Cosine Algorithm (SCA), TF-IDF, BERT, Word2Vec, GloVe 17, 18.Bilinmesi Gereken Anahtar Kelimeler: Particle Swarm Optimization (PSO), Collaborative Filtering, Word Embedding, Rating, Review 16, 17.Veri Seti(leri): Amazon Veri Setleri (Dijital müzik, Enstrüman, Otomotiv, Ofis ürünleri, Gurme gıda vb.) 19.Yenilik / Ne Sunuyor?: Doğal Dil İşleme (NLP) metotları ile yorumlardan matris çıkarır ve elde edilen matris özelliklerinin optimum ağırlıklandırılması işlemi için doğrudan Parçacık Sürü Optimizasyonu'nu (PSO) kullanır 17, 20.Karşılaştırma Yöntemleri: GA-BERT, GA-word2vec, GA-GloVe, SCA-BERT, SCA-GloVe gibi farklı meta-sezgisel + NLP kombinasyonları 20.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE (Ortalama Mutlak Hata) ve Standart Sapma (STD) ile değerlendirilmiş; en düşük hata oranı (0.6304 MAE) PSO-BERT modelinde bulunmuştur 20.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Hibrit MF mimarinizde kullanacağınız Meta-sezgisel algoritmanın (özellikle ağırlık optimizasyonunda) sistemle nasıl entegre edilebileceği ve matris üzerindeki latent faktörlerin nasıl evrimsel olarak iyileştirilebileceği konusunda birebir örnek teşkil eder 17, 18.Cold Start ele alınmış mı?: Doğrudan ele alınmıştır; metin (review) ve etiket bilgilerini modele dahil etmesinin asıl nedeni "Data Sparsity" (veri seyrekliği) yani Cold-Start problemine dayanıklı bir yapı oluşturmaktır 17.
Makale 4Makale Adı & Yıl: A recommender system with multi-objective hybrid Harris Hawk optimization for feature selection and disease diagnosis (2025) 21.Yazar(lar): Madhusree Kuanr, Puspanjali Mohapatra 21.Dergi/Konferans: Healthcare Analytics 21.Amaç & Katkı: Teşhis (hastalık) öneri sistemlerinde büyük boyutlu veri setlerindeki özellikleri sadeleştirmek için çok amaçlı bir meta-sezgisel algoritma kullanarak optimum doğruluğa ulaşmak 21, 22.Kullanılan Algoritmalar/Yöntemler: Multi-Objective Hybrid Harris Hawk Optimization (MOGAHHO), Genetik Algoritma (MOGA), Çok Kriterli Karar Verme (TOPSIS), Autoencoder, PCA, SVD 23-25.Bilinmesi Gereken Anahtar Kelimeler: Recommender system, Multi-objective feature selection, Automated machine learning, Harris Hawk Optimization 21, 26.Veri Seti(leri): Sağlık verileri (Diyabet, ILPD, Dermatoloji, Kalp hastalıkları, COVID-19 vb.) 27.Yenilik / Ne Sunuyor?: Meta-sezgisel bir optimizasyon algoritmasını (HHO) mutasyon ve çaprazlama operatörleri ile güçlendirerek gürültülü ve büyük matrislerde en etkili özellik matrisinin seçilmesini sağlar 23, 25.Karşılaştırma Yöntemleri: MOGA, MOHHO, Autoencoder, PCA, SVD ve sadece özellik seçimi yapılmayan ham veri kullanımları 24, 27.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Balanced Accuracy (BA), MCC, Bookmaker Informedness (BM), Markedness (MK) ve İşlem Süresi (RT); önerilen model boyut küçültmesine rağmen en yüksek hassasiyete ulaşmıştır 24, 27.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Büyük matrislerin çarpanlarına ayrılması (SVD/MF) sırasında karşınıza çıkacak çok boyutluluk (dimensionality) problemini bir Meta-sezgisel algoritma (özellik seçimi ve matris optimizasyonu) ile nasıl sadeleştirebileceğinizi kanıtlayan modern bir vakadır 25.Cold Start ele alınmış mı?: Yüksek boyutlu matrislerin yarattığı veri gürültüsü ve seyrekliğine karşı koyduğu (özellik indirgeme) için zımni olarak seyrek sistemlerde (sparsity) model dayanıklılığı sağlamaktadır 25.

Makale 5Makale Adı & Yıl: A grasshopper optimization algorithm-based movie recommender system (2024) 1.Yazar(lar): N. Ganesh, R. Shankar, R. Čep vd. (Referanslardan anlaşıldığı kadarıyla) 2.Dergi/Konferans: Multimedia Tools and Applications 3.Amaç & Katkı: İşbirlikçi filtrelemedeki veri seyrekliği, ölçeklenebilirlik ve soğuk başlangıç (cold start) gibi sorunları aşmak için kullanıcılara daha isabetli film önermek 1.Kullanılan Algoritmalar/Yöntemler: Çekirge Optimizasyon Algoritması (Grasshopper Optimisation Algorithm - GOA) ve K-means kümeleme 4, 5.Bilinmesi Gereken Anahtar Kelimeler: Grasshopper optimisation algorithm, metaheuristic, k-means, cold-start, collaborative filtering 1, 4.Veri Seti(leri): Makaleye ait film tercih veri setleri 5.Yenilik / Ne Sunuyor?: K-means, PCA-k-means ve SOM kümeleme yöntemlerine kıyasla veriyi daha iyi ayrıştıran hibrit bir "GOA-k-means" optimizasyon yaklaşımı sunar 5.Karşılaştırma Yöntemleri: Standart k-means, PCA-k-means, SOM clustering ve PCA-SOM 5.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Kümeleme doğruluğu bazında test edilmiş ve mevcut yöntemlere göre üstün (superior) bir alternatif olduğu kanıtlanmıştır 5.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF aşamasından önce veri setini kümelemek veya MF matrisindeki gizli özellikleri aramak için çekirge (GOA) gibi güncel bir meta-sezgiselin nasıl entegre edileceğini gösterir 4, 5.Cold Start ele alınmış mı?: Evet, makale açıkça yeni ürün/kullanıcılar için veri azlığından kaynaklanan "Cold Start" ve veri seyrekliği (sparsity) problemlerini çözmeye odaklanmıştır 1, 5.
Makale 6Makale Adı & Yıl: A new recommendation system using map-reduce-based tournament empowered Whale optimization algorithm (2021) 6.Yazar(lar): S. Yi, X. Liu, H. Mittal, M. Saraswat vd. (Referanslardan anlaşılan ana çalışma grupları) 7, 8.Dergi/Konferans: Complex & Intelligent Systems 6.Amaç & Katkı: Büyük veri (Big Data) setleri üzerinde kümeleme kalitesini artırarak tavsiye sistemlerinin performansını iyileştirmek 9, 10.Kullanılan Algoritmalar/Yöntemler: Balina Optimizasyon Algoritması (Whale Optimization Algorithm - WOA) ve Map-Reduce mimarisi 9, 8.Bilinmesi Gereken Anahtar Kelimeler: Whale optimization algorithm, MapReduce, Meta-heuristic, Clustering 9, 8.Veri Seti(leri): Iris, CMC, Wine ve Vovel gibi milyonlarca nesneye (Data objects) sahip büyük ölçekli replike edilmiş veri setleri 10.Yenilik / Ne Sunuyor?: Standart Balina Optimizasyonunu, devasa matrisleri işleyebilmek adına Map-Reduce (paralel işleme) yapısına ve turnuva seçimine (tournament empowered) entegre eder 6, 10.Karşılaştırma Yöntemleri: ICS, EGWO (Grey Wolf), SCA, WOA (standart) ve TWOA 11, 10.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Ortalama uygunluk değeri (Mean fitness value) ve Standart Sapma; önerilen hibrit model en iyi (Best) değerlere ulaşmıştır 11, 10.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Sisteminize çok büyük (milyonluk) bir kullanıcı-film matrisi (Big Data) geldiğinde, MF + Meta-sezgisel optimizasyonunun hesaplama süresini düşürmek için paralel işlemeye (MapReduce) nasıl uyarlanabileceğine dair harika bir altyapı sunar 10.Cold Start ele alınmış mı?: Hayır, odak noktası cold-start'tan ziyade yüksek boyutlu "büyük veri"lerdeki (high-dimensional) işlem karmaşasını ve ölçeklenebilirliği (scalability) çözmektir 10.
Makale 7Makale Adı & Yıl: Movie recommender system with metaheuristic artificial bee (2018) 12, 13.Yazar(lar): Rahul Katarya 13.Dergi/Konferans: Neural Computing and Applications 14.Amaç & Katkı: İşbirlikçi filtreleme (CF) tabanlı sistemlerdeki seyrek veri (data sparsity) ve soğuk başlangıç zorluklarını aşmak 12, 15.Kullanılan Algoritmalar/Yöntemler: Yapay Arı Kolonisi (ABC), K-Means Kümeleme ve Pearson Benzerliği 12.Bilinmesi Gereken Anahtar Kelimeler: Collaborative filtering, Artificial bee colony, k-mean, Pearson similarity 12.Veri Seti(leri): MovieLens veri seti 15, 16.Yenilik / Ne Sunuyor?: K-means kümelemesi ile ABC (Yapay Arı Kolonisi) algoritmasını birleştirerek "k-mean-ABC" adı verilen ve bellek tabanlı tavsiye kalitesini artıran bir model sunar 15.Karşılaştırma Yöntemleri: Temel memory-based (bellek tabanlı) sistemler ile klasik SVM veya PCA kullanan yapılar 15.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE (Ortalama Mutlak Hata) ve Precision (Kesinlik) metriklerinde değerlendirilmiş, hata oranları düşürülmüştür 16.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Doğrudan meta-sezgisel bir swarming (sürü) algoritmasının (ABC) tavsiye sisteminde Pearson benzerliği ile birlikte nasıl kullanılacağının mimarisini verir 12.Cold Start ele alınmış mı?: Evet, makalenin ana çıkış noktalarından biri yeni kullanıcıların sisteme girmesiyle oluşan "Cold Start" problemidir 12.
Makale 8Makale Adı & Yıl: Recommender system with grey wolf optimizer and FCM (2018) 13.Yazar(lar): Rahul Katarya 13.Dergi/Konferans: Neural Computing and Applications 14.Amaç & Katkı: Klasik işbirlikçi sistemlerin yetersiz kaldığı durumlarda kullanıcı davranışlarını bulanık mantık (Fuzzy) ve kurt sürüsü zekasıyla daha iyi sınıflandırarak öneri isabetini artırmak 13.Kullanılan Algoritmalar/Yöntemler: Grey Wolf Optimizer (Gri Kurt Optimizasyonu - GWO), Fuzzy C-Means (FCM), Collaborative Filtering 13.Bilinmesi Gereken Anahtar Kelimeler: Recommender systems, Collaborative filtering, Gray wolf optimizer, Fuzzy c-mean 13.Veri Seti(leri): MovieLens veri seti 16.Yenilik / Ne Sunuyor?: K-means gibi keskin kümeleme yerine FCM (Bulanık c-ortalamalar) kullanıp, küme merkezlerini meta-sezgisel GWO ile optimize eden esnek bir sistem geliştirir 13.Karşılaştırma Yöntemleri: Mevcut geleneksel e-ticaret tavsiye sistemleri (geleneksel bellek tabanlı işbirlikçi filtreleme vb.) 13, 16.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Precision (Kesinlik) ve MAE metrikleri ile test edilmiş, diğer algoritmalardan bariz şekilde iyi performans göstermiştir 16.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF algoritmanızdaki özellik matrislerini (feature matrices) bulanık mantık ile esneterek (fuzzy approach) GWO gibi başarılı bir meta-sezgisel ile nasıl eğitebileceğinizi gösterir 13.Cold Start ele alınmış mı?: Evet, açık bir şekilde kullanıcının yeterli profil veya puanı olmadığı durumlar (Cold-Start) ana problemlerden biri olarak ele alınmıştır 13.
Makale 9Makale Adı & Yıl: Proposing improved meta-heuristic algorithms for clustering... (2020) 17.Yazar(lar): R. Rashidi, K. Khamforoosh, A. Sheikhahmadi vd. 18.Dergi/Konferans: Physica A: Statistical Mechanics and Its Applications 18 (Springer veri tabanı / makale ID'sinden) 17.Amaç & Katkı: Tavsiye sistemlerinde profili belirsiz olan "Gray sheep" (gri koyun) kullanıcılarını, başarılı kümeleme merkezleri bularak beyaz kullanıcılardan yüksek doğrulukla ayırmak 17.Kullanılan Algoritmalar/Yöntemler: MkMeans++, Firefly (Ateşböceği), Cuckoo Search (Guguk Kuşu), Krill Herd algoritmaları 17, 19.Bilinmesi Gereken Anahtar Kelimeler: MkMeans++, Gray sheep users, Firefly, Cuckoo, Krill, Meta-heuristic 17, 20.Veri Seti(leri): Kullanıcı tercih (preference) matrisleri 21.Yenilik / Ne Sunuyor?: MkMeans++ algoritmasını üç farklı popülasyon tabanlı meta-sezgisel algoritma (CuckooMkMeans++, FireflyMkMeans++, KrillMkMeans++) ile besleyerek yerel optimizasyona (local optima) düşmeyi engeller 17, 20.Karşılaştırma Yöntemleri: Geleneksel k-Means, Ant Colony (Karınca), Particle Swarm (Parçacık Sürü) algoritmaları 21.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Yerel optimizasyondan kaçınma ve kümeleme hassasiyeti (Accuracy); hibrit algoritmalarla gri koyun kullanıcı ayrımında keskinlik artışı 17.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Matris Çarpanlara ayırma öncesi matrisi seyrekleştiren tutarsız veya tahmin edilemez kullanıcı davranışlarını (gray sheep) meta-sezgisel ile ayıklayarak matrisinizi temizlemeniz için çok iyi bir referanstır 17, 21.Cold Start ele alınmış mı?: "Gray sheep" problemi doğrudan incelenmiş; zevkleri ve davranışları eşleştirilemeyen bu kullanıcı tipi Cold Start probleminin en büyük varyasyonlarından biridir 17, 22.
Makale 10Makale Adı & Yıl: Hybrid crow search and uniform crossover algorithm-based clustering for top-N recommendation system (2021) 23.Yazar(lar): M. Wasid, R. Ali vd. (Makale içindeki kaynak referans dizinlerinden alınmıştır) 24, Misr International University & Koszalin University (Araştırma kurumları) 23.Dergi/Konferans: Neural Computing and Applications 25.Amaç & Katkı: Top-N tavsiye (en iyi N önerisi) sistemlerindeki performansı, arama uzayındaki çeşitliliği (diversity) artırarak iyileştirmek 26.Kullanılan Algoritmalar/Yöntemler: Crow Search Algorithm (Karga Arama Algoritması - CSA), Genetik Uniform Crossover (HCSUC), Clustering, Collaborative Filtering 23, 26.Bilinmesi Gereken Anahtar Kelimeler: Recommender system, Collaborative filtering, Crow search algorithm, Uniform crossover 23, 26.Veri Seti(leri): 90 kullanıcılı özel test kümeleri ve klasik test matrisleri 25.Yenilik / Ne Sunuyor?: Meta-sezgisel "Karga Arama" algoritmasının içine Genetik Algoritmaların "Çaprazlama (Crossover)" operatörünü katarak (HCSUC modeli) yerel minimum tuzaklarına düşmeyi engeller 26.Karşılaştırma Yöntemleri: Standart Crow Search (CSA), African Buffalo Optimization (ABO) ve PSO 26.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): RMSE (Kök Ortalama Kare Hatası) metrikleri kullanılmış, HCSUC modeli RMSE bazında (Örn: 0.3368 ve 0.3864 değerleriyle) PSO ve ABO'yu geride bırakmıştır 25, 26.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Meta-sezgisel algoritmanızın (MF ağırlıklarını ararken) yerel minimuma takılmasını engellemek için algoritma içerisine evrimsel bir "Crossover" adımı nasıl eklenebileceğini gösterir 26.Cold Start ele alınmış mı?: Spesifik olarak belirtilmemiş; problem uzayında yerel minimumdan kaçınmaya ve isabet oranına (Top-N doğruluğuna) odaklanılmıştır 26.
(Not: Sisteme yüklediğiniz PDF ve text datası çok büyük bir algoritma derleme (review) kütüphanesini kapsıyor. Kalan makaleler de tıbbi görüntüleme (mammogram), enerji dağıtımı (PSO), veya farklı matematiksel optimizasyon senaryolarında kullanılan SMA (Slime Mould), FHO (Fire Hawk) gibi meta-sezgiselleri tanıtıyor. Recommender Systems ve Matris Çarpanlarına Ayırma ile en ilgili ana küme yukarıdaki gibidir.)

Makale 11Makale Adı & Yıl: A collaborative recommender system enhanced with particle swarm optimization technique (2016) 1.Yazar(lar): Rahul Katarya, Om Prakash Verma 1.Dergi/Konferans: Multimedia Tools and Applications 1.Amaç & Katkı: İşbirlikçi filtreleme tabanlı film öneri sistemlerinde kümeleme doğruluğunu ve tavsiye isabetini artırmak için birden fazla algoritmayı birleştirmek 2, 3.Kullanılan Algoritmalar/Yöntemler: Parçacık Sürü Optimizasyonu (PSO), K-Means, Bulanık C-Ortalamalar (Fuzzy C-Means - FCM), Type Division Method 2.Bilinmesi Gereken Anahtar Kelimeler: Recommender system, Computational intelligence, Fuzzy C-means, Collaborative filtering, Movie 1.Veri Seti(leri): MovieLens 4.Yenilik / Ne Sunuyor?: Filmleri türlerine (type division) ayırarak K-Means ile başlangıç merkezlerini belirler; bu merkezleri PSO ile optimize ederek FCM'ye verir ve kümeleme hatalarını minimize eder 2, 5.Karşılaştırma Yöntemleri: PCA-GAKM, PCA-SOM, SOM-Cluster, K-Means Clustering, GA-KM Cluster 3.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE (Ortalama Mutlak Hata) metrikleri kullanılmış; önerilen KM-PSO-FCM mimarisi diğer sistemlerden daha düşük hata (daha yüksek doğruluk) vermiştir 3, 5.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: PSO'nun bir tavsiye sisteminde nasıl küme merkezlerini (ve dolaylı yoldan matris ağırlıklarını) optimize edeceğine dair temel bir referans çalışmasıdır 5.Cold Start ele alınmış mı?: Veri dağılımını iyileştirse de metinde doğrudan "Cold Start" problemine odaklanılmamıştır 2.
Makale 12Makale Adı & Yıl: A Recommender System based on Invasive Weed Optimization Algorithm (2007) 6.Yazar(lar): Hoda Sepehri Rad, Caro Lucas 6.Dergi/Konferans: IEEE Congress on Evolutionary Computation (CEC) 7.Amaç & Katkı: Geleneksel kullanıcı tabanlı benzerlik hesaplamasını geliştirmek için "önceliklendirilmiş kullanıcı profili" yaklaşımını kullanarak her kullanıcının profil özelliklerine (yaş, cinsiyet vb.) en uygun öncelik ağırlıklarını atamak 6, 8.Kullanılan Algoritmalar/Yöntemler: İstilacı Ot Optimizasyonu (Invasive Weed Optimization - IWO), Pearson Korelasyonu, İşbirlikçi Filtreleme 6, 9.Bilinmesi Gereken Anahtar Kelimeler: Recommender Systems, Invasive Weed Optimization, Prioritized user-profile, Collaborative filtering 6.Veri Seti(leri): MovieLens 10.Yenilik / Ne Sunuyor?: Kullanıcı benzerliğini hesaplarken (Pearson) matris özellik ağırlıklarını optimum hale getirmek için biyolojiden esinlenen IWO (İstilacı Ot) algoritmasını ilk kez bir tavsiye sisteminde kullanır 6.Karşılaştırma Yöntemleri: Genetik Algoritma (GA), Parçacık Sürü Optimizasyonu (PSO), Standart Kullanıcı Tabanlı Pearson algoritması (PA) 6, 11.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): RMSE üzerinden test edilmiş ve IWO tabanlı model, GA ve PSO tabanlı sistemlere kıyasla daha düşük hata payıyla en iyi tahmini sağlamıştır 6, 12, 13.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Kendi MF modelinizde faktörlere (veya özellik matrislerine) atanacak ağırlıkları optimize etmek için meta-sezgisel (IWO, PSO, GA vb.) algoritmaların doğrudan entegrasyon mantığını gösterir 9.Cold Start ele alınmış mı?: Doğrudan cold start yerine aktif kullanıcıların verisini kullanarak benzerlik bulma olasılığını artırmaya odaklanılmıştır 14.
Makale 13Makale Adı & Yıl: Personalized E-commerce Recommendation System using Marine Predator Algorithm with Gated Recurrent Unit (2024) 15.Yazar(lar): Suvarna Sunil Kumar 15.Dergi/Konferans: 2024 International Conference on Distributed Systems, Computer Networks and Cybersecurity (ICDSCNC) - IEEE 15.Amaç & Katkı: E-ticaret platformlarındaki bilgi karmaşasını azaltarak ürün ve kullanıcı yorumlarından çıkarılan verilerle derin öğrenme tabanlı isabetli kişiselleştirilmiş tavsiyeler üretmek 16, 17.Kullanılan Algoritmalar/Yöntemler: Deniz Yırtıcısı Algoritması (Marine Predator Algorithm - MPA), Gated Recurrent Unit (GRU), Doğal Dil İşleme (TF-IDF, Stemming, Lemmatization) 16, 18.Bilinmesi Gereken Anahtar Kelimeler: E-commerce Recommendation System, TF-IDF, Marine Predator Algorithm, Gated Recurrent Unit 18.Veri Seti(leri): Amazon Product Review ve Retail Rocket veri setleri 18.Yenilik / Ne Sunuyor?: TF-IDF ile ağırlıklandırılan yorum verilerini işlemek ve tavsiye hassasiyetini maksimize etmek için Derin Öğrenme (GRU) ağının mimari parametrelerini MPA isimli meta-sezgisel ile optimize eder 18, 19.Karşılaştırma Yöntemleri: Farklı sınıflandırıcılar ve temel optimizasyon tabanlı makine öğrenimi modelleri (Metinde detaylı liste kısıtlıdır) 20, 21.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Accuracy, Precision@k, Recall, MRR@k, F1-score 20.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF kullanmasa bile, çok güncel bir "Derin Öğrenme + Yeni Nesil Meta-sezgisel (MPA)" hibrit model örneğidir; mimarinizi derin öğrenme bileşenleriyle zenginleştirmek isterseniz iyi bir kılavuzdur 18.Cold Start ele alınmış mı?: Metin ve yorum analizine (NLP) odaklanıldığı için cold start probleminden doğrudan bahsedilmemiştir 16.
Makale 14Makale Adı & Yıl: Hybrid Sparrow Clustered (HSC) Algorithm for Top-N Recommendation System (2022) 22.Yazar(lar): Bharti Sharma, Adeel Hashmi, Charu Gupta, vd. 22.Dergi/Konferans: Symmetry (MDPI) 22.Amaç & Katkı: İşbirlikçi filtrelemedeki benzerlik sorunlarını aşmak için kullanıcıları en ideal kümelere (cluster) ayırıp aktif kullanıcıya en iyi N ürünü (Top-N) tavsiye etmek 23, 24.Kullanılan Algoritmalar/Yöntemler: Serçe Arama Algoritması (Sparrow Search Algorithm - SSA), K-Nearest Neighbors (KNN), Kümeleme (Clustering) 24.Bilinmesi Gereken Anahtar Kelimeler: Top-N Recommendation System, Sparrow Search, Clustering, KNN 22.Veri Seti(leri): Jester, MovieLens vb. 4 farklı veri seti (metinde k-kümeler üzerinden film/şaka önerileri test edilmiş) 25, 26.Yenilik / Ne Sunuyor?: Kümelerin merkezlerini optimize etmek ve kullanıcı gruplarını en uygun şekilde atamak için doğadan esinlenen Serçe (Sparrow) arama algoritmasını kullanır; KNN ile de komşu kümeden en yüksek puanlı öğeleri çeker 24, 27.Karşılaştırma Yöntemleri: Temel kümeleme tabanlı (K-Means) ve filtreleme yöntemleri 23.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE, RMSE, Standard Deviation (SD), t-value, Precision, Recall metrikleri ile değerlendirilmiştir 25, 28.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Ön işleme adımında (MF'den önce) matrisin boyutunu veya veri karmaşıklığını "optimize edilmiş alt kümelere" bölmek için bir meta-sezgisel (SSA) kullanımının tipik bir örneğidir 24.Cold Start ele alınmış mı?: Spesifik olarak geçmemektedir 26.
Makale 15Makale Adı & Yıl: Emotion-Aware Movie Recommendation System using Hybrid Dipper-Throated and Grey Wolf Optimization with Autoencoder and Hybrid Filtering (2025) 29.Yazar(lar): Supriya L P, Rashmita Khilar 29.Dergi/Konferans: 2025 6th International Conference on Data Intelligence and Cognitive Informatics (ICDICI) - IEEE 29.Amaç & Katkı: Kullanıcının yüz ifadelerinden (duygu durumu) elde edilen verilerle hibrit filtrelemeyi birleştirerek kullanıcının o anki ruh haline en uygun filmleri önermek 30, 31.Kullanılan Algoritmalar/Yöntemler: Hybrid Dipper-Throated Optimization (DTO) ve Grey Wolf Optimization (GWO), Autoencoder (Otokodlayıcılar), Hybrid Filtering (CF + Content-Based Filtering) 31, 32.Bilinmesi Gereken Anahtar Kelimeler: Recommendation system, Autoencoder, Collaborative filtering, Content-based filtering, Feature Engineering, Emotion-Aware 30.Veri Seti(leri): Yüz ifadeleri için FER-2013 veri seti ve film veri setleri 32.Yenilik / Ne Sunuyor?: Gizli faktörleri (latent features) öğrenmek için Autoencoder kullanır; duygu analizi ve tavsiye eşleşmesini optimize etmek için iki farklı meta-sezgisel algoritmayı (DTO ve GWO) yepyeni bir melez formda (AHDGFS) çalıştırır 31, 32.Karşılaştırma Yöntemleri: Standart CF-MRS, DABF, USDM, AFEM gibi sistemler 33.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Accuracy, Sensitivity, Specificity grafikleri kullanılarak en yüksek doğruluk elde edilmiştir 33.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Kendi tasarlayacağınız hibrit meta-sezgisel (birden çok algoritmanın birleşimi) ile "gizli faktör öğrenimini" (MF veya Autoencoder) birleştiren muazzam bir modern vakadır 31, 32.Cold Start ele alınmış mı?: Model içerisinde "Content-Based Filtering (İçerik tabanlı filtreleme)" ile birleşik bir Hybrid Filtering kullanıldığından zımni olarak seyrek veri ve cold start engellerine karşı dayanıklı tasarlanmıştır 31, 32.
Makale 16Makale Adı & Yıl: Sparse Matrix Factorization Algorithm for Real-Time Movie Recommendation Systems (2025) 34.Yazar(lar): Ankit Verma, Gundavarapu Mallikarjuna Rao 34.Dergi/Konferans: 2025 3rd International Conference on Cyber Resilience (ICCR) - IEEE 34.Amaç & Katkı: Matrislerin seyrekliği (data sparsity) ve gerçek zamanlı dinamik güncelleme ihtiyacı gibi geleneksel zorlukları ölçeklenebilir ve hafif bir matris çarpanlarına ayırma yöntemiyle çözmek 35, 36.Kullanılan Algoritmalar/Yöntememler: Seyrek Matris Çarpanlarına Ayırma (Sparse Matrix Factorization - SMF), Stochastic Gradient Descent (Stokastik Gradyan İnişi - SGD), Online Updating 35, 37.Bilinmesi Gereken Anahtar Kelimeler: Real-Time Movie Recommendation Systems, Sparse Matrix Factorization, Stochastic Gradient Descent (SGD) 35, 37.Veri Seti(leri): MovieLens 1M 38.Yenilik / Ne Sunuyor?: Aşırı öğrenmeyi (overfitting) engelleyen geliştirilmiş SGD optimizasyonu ve yeni gelen kullanıcı/öğe etkileşimlerini matrisi baştan hesaplamadan dinamik olarak (online update) öğrenen gerçek zamanlı bir mimari sunar 35, 39.Karşılaştırma Yöntemleri: Klasik/Geleneksel tavsiye yöntemleri 35.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Precision@N, Recall@N kullanılmış; gerçek zamanlı senaryolarda verimlilik ve isabet kazancı kanıtlanmıştır 40, 41.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF tabanlı modelinizin "Gerçek Zamanlı (Online)" çalışması veya ağırlıkların (Stokastik Gradyan İnişi vb.) nasıl güncellenebileceği konusunda güçlü bir zemin sunar; bu döngüye meta-sezgisel ağırlık optimizasyonunu ekleyebilirsiniz 37, 42.Cold Start ele alınmış mı?: Doğrudan ve net ele alınmıştır; tasarlanan Pseudo kod içindeki "Cold-Start Managing" modülü sayesinde yeni bir kullanıcı veya öğe geldiğinde gizli vektörler rastgele küçük değerlerle başlatılır ve veri geldikçe yavaşça güncellenir 39, 42.

Makale 17Makale Adı & Yıl: A survey of recommender systems with multi-objective optimization (2022) 1.Yazar(lar): Y. Zheng, David (Xuejun) Wang 1.Dergi/Konferans: Neurocomputing 1.Amaç & Katkı: Tavsiye sistemlerinde ortaya çıkan çok amaçlı (multi-objective) optimizasyon problemlerini çözmek için doğru metotların seçilmesine yönelik kapsamlı bir kılavuz ve iş akışı sunmak 1.Kullanılan Algoritmalar/Yöntemler: Çok Amaçlı Evrimsel Algoritmalar (MOEA), Sürü Zekası (Swarm Intelligence), MOGA, NSGA 2, 3.Bilinmesi Gereken Anahtar Kelimeler: Multi-objective optimization, Evolutionary algorithms, Recommender systems, Pareto optimal 1, 3.Veri Seti(leri): Derleme (survey) makalesi olduğu için genel veri setleri üzerinden analiz yapılmıştır.Yenilik / Ne Sunuyor?: Farklı paydaşların (kullanıcı, satıcı vb.) zıt hedeflerini aynı anda optimize edebilmek için evrimsel ve meta-sezgisel algoritmaların tavsiye sistemlerine nasıl entegre edileceğini sistematize eder 4.Karşılaştırma Yöntemleri: Mevcut çok amaçlı (multi-task ve multi-objective) tavsiye sistemleri karşılaştırılmıştır 5, 6.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): İnceleme (survey) makalesi.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Kuracağınız hibrit modelin sadece doğruluğu (accuracy) değil; aynı zamanda çeşitliliği (diversity) ve yeniliği (novelty) de hedefleyen "çok amaçlı bir meta-sezgisel" olarak nasıl uyarlanabileceğini gösterir.Cold Start ele alınmış mı?: Çoklu paydaş gereksinimlerini dengelerken zımni olarak değinilmiştir ancak asıl odak Çok Amaçlı Optimizasyondur (MOO) 4.
Makale 18Makale Adı & Yıl: Attention matrix factorization (2024) 7.Yazar(lar): C. Ming, Y. Liu, Z. Shi 7.Dergi/Konferans: Symmetry (MDPI) 7.Amaç & Katkı: Matris çarpanlarına ayırma (MF) modelini geleneksel iç çarpım (dot product) sınırlarından kurtararak, kullanıcı ve öğe gizli faktörleri (latent features) arasındaki farklı boyut korelasyonlarını "Attention" mekanizması ile güçlendirmek 8.Kullanılan Algoritmalar/Yöntemler: Matris Çarpanlarına Ayırma (MF), Slide-Attention Mechanism, Çok Katmanlı Algılayıcı (MLP), Gradient Descent 9, 8, 10.Bilinmesi Gereken Anahtar Kelimeler: Attention mechanism, Matrix factorization, Slide-attention, Latent features 8.Veri Seti(leri): MovieLens 100K, MovieLens 1M 11.Yenilik / Ne Sunuyor?: Klasik Attention yerine q ve k özelliklerinin boyutlar arası etkileşim skorlarını daha iyi yakalayan "Slide-attention" algoritmasını MF ile birleştirir 12, 13.Karşılaştırma Yöntemleri: MLP katman sayılarının ve farklı gizli nöron sayılarının etkileri kendi içinde karşılaştırılmıştır 14, 15.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE ve RMSE metrikleri kullanılmış, sinir ağı boyutları değiştikçe hataların azaldığı grafikte gösterilmiştir 14, 11.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF aşamasından çıkan P ve Q (kullanıcı/öğe) matrislerini klasik doğrusal (linear) çarpmak yerine, özellikleri meta-sezgisel veya attention algoritmalarıyla nasıl daha hassas eşleştirebileceğinize dair çok iyi bir referanstır.Cold Start ele alınmış mı?: Modelin hedefi doğrudan veri temsiliyetini (representation) artırmak olup Cold-start'a özgü bir detay verilmemiştir.
Makale 19Makale Adı & Yıl: Combining Cmab with Matrix Factorization and Clustering For Enhanced Movie Recommendations (2025) 16, 17.Yazar(lar): J. Zhao (Ref 1), ITM Web of Conferences Yazarları 16, 18.Dergi/Konferans: ITM Web of Conferences (CSEIT 2025) 17.Amaç & Katkı: Öneri sistemlerindeki hesaplama maliyetini düşürmek ve cold-start problemine dinamik bir "keşfet-sömür (explore-exploit)" dengesi getirmek 16.Kullanılan Algoritmalar/Yöntemler: Contextual Multi-Armed Bandit (LinUCB, UCB1, TS), FunkSVD (Matris Çarpanlarına Ayırma), K-means Kümeleme 16, 19.Bilinmesi Gereken Anahtar Kelimeler: Multi-armed bandit, FunkSVD, K-means Clustering, Regret convergence 16, 19, 20.Veri Seti(leri): 3952 film içeren kullanıcı-film puanlama veri seti (büyük ihtimalle MovieLens) 19.Yenilik / Ne Sunuyor?: 3952 filmi doğrudan MAB (Multi-Armed Bandit) algoritmasına sokmak yerine, K-means ile 96 kümeye ayırarak arama uzayını daraltır ve FunkSVD ile tahmin matrisi çıkarır 19, 17.Karşılaştırma Yöntemleri: LinUCB, UCB1 ve Thompson Sampling (TS) algoritmalarının kendi aralarında kıyası yapılmıştır 20, 21.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Kümülatif Pişmanlık (Cumulative Regret) ve Regret Convergence Slope metriği kullanılmıştır; LinUCB modeli (eğim ≈ 0.0718) en stabil ve iyi performansı sergilemiştir 20, 21.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF (FunkSVD) modelinizin üzerine veya öncesine meta-sezgiseli/kümelemeyi ekleyerek boyut küçültme (dimensionality reduction) yapmanın canlı bir kanıtıdır.Cold Start ele alınmış mı?: Doğrudan ele alınmıştır; Bandit (MAB) algoritmalarının kullanılmasının ana sebebi yeni kullanıcı/öğelerdeki "Cold Start" problemini çözmektir 16.
Makale 20Makale Adı & Yıl: GAN-based matrix factorization for recommender systems (2022) 22.Yazar(lar): Ervin Dervishaj, Paolo Cremonesi 22.Dergi/Konferans: ACM Symposium on Applied Computing (SAC) 23.Amaç & Katkı: Çekişmeli Üretici Ağlar (GAN) kullanarak, geleneksel matris çarpanlarına ayırma (MF) modelinin öğrenme sürecini farklı bir mimariye oturtarak kullanıcı profil tahminini iyileştirmek 24, 25.Kullanılan Algoritmalar/Yöntemler: Generative Adversarial Networks (GANs), Matrix Factorization, Mini-max Optimizasyonu 26, 25.Bilinmesi Gereken Anahtar Kelimeler: GANMF, Generative Adversarial Network, Matrix Factorization, Discriminator, Generator 22, 26, 25.Veri Seti(leri): Çeşitli URM (Kullanıcı Puan Matrisi - User Rating Matrix) splitleri 23.Yenilik / Ne Sunuyor?: Üretici (Generator) ağın doğrudan Matris Çarpanlarına Ayırma (MF) mimarisi olarak konumlandırıldığı (embedding katmanlarıyla) özel bir GANMF pseudo-kodu sunar 25.Karşılaştırma Yöntemleri: Geleneksel MF ve IRGAN (Information Retrieval GAN) modelleri 26.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): NDCG@5, NDCG@20, MAP@5, MAP@20 ile ölçüm yapılmış, listelerin kalitesi test edilmiştir 23.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF matrisinizi optimize etmek için tasarlayacağınız meta-sezgisel yapının yerine, literatürdeki "Derin Öğrenme" (GAN vb.) bazlı diğer hibrit optimizasyon mimarilerine karşı nasıl konumlandıracağınızı görmenizi sağlar.Cold Start ele alınmış mı?: Geçmiş kullanıcı profillerinin üretilmesi (generation) üstünden ilerlese de ana odak doğrudan cold-start değil, üretim-ayırt etme (discriminative) dengesidir.
Makale 21Makale Adı & Yıl: IMPROVED PROBABILISTIC MATRIX FACTORIZATION MODEL FOR SPARSE DATASETS (2014) 27.Yazar(lar): Yılmaz Ar (Doktora Tezi) 27.Dergi/Konferans: ODTÜ (METU), Bilişim Sistemleri (Doktora Tezi) 27, 28.Amaç & Katkı: Olasılıksal Matris Çarpanlarına Ayırma (PMF) algoritmalarında "gizli vektörlerin (latent vectors) başlangıç değerlerinin (initialization)" tahmin başarısı üzerindeki yüksek etkisini kanıtlamak 29.Kullanılan Algoritmalar/Yöntemler: Probabilistic Matrix Factorization (PMF), INMED, Geliştirilmiş INMED I-IV, Gaussian ve Üniform başlatma 29, 30, 31, 32, 33.Bilinmesi Gereken Anahtar Kelimeler: Probabilistic Matrix Factorization, Latent Vectors, Recommender Systems, Initialization, Sparse Datasets 34.Veri Seti(leri): Epinions, LastFM, MovieLens dahil tam 32 farklı (gerçek ve sentetik) veri seti 35, 36.Yenilik / Ne Sunuyor?: Klasik rastgele (Gaussian) atamalar yerine, veri setinin "seyrekliği (sparsity)" ve "çarpıklığı (skewness)" gibi özellikleri formülize ederek P ve Q vektörlerini başlatan beş yeni INMED başlatma metodu sunar 30, 31, 32, 33.Karşılaştırma Yöntemleri: BPMF, Uniform, Gaussian, klasik PMF ve farklı kesme katsayılarıyla (C-0.0 ... C-0.8) oluşturulan temel metotlar 35, 37, 38.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE ve RMSE metrikleri için ciddi "t-testi" istatistiksel analizleri yapılmış; önerilen gelişmiş atamalar hata oranlarını (özellikle aşırı seyrek veride) belirgin şekilde düşürmüştür 35, 37, 39.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF kurarken en büyük sıkıntılardan biri P ve Q matrislerinin "başlangıç değerleridir (initialization)". Meta-sezgisel algoritmanızı, bu tezdeki gibi, MF'in P ve Q başlangıç popülasyonunu atamak için de kurgulayabilirsiniz.Cold Start ele alınmış mı?: Doğrudan hedef kitlesi zaten çok seyrek (sparsity) veri setleridir; bu da literatürdeki Cold-Start sorununun en temel nedenidir 27, 29.
Makale 22Makale Adı & Yıl: Kernelized Deep Learning for Matrix Factorization (2024) 40.Yazar(lar): Xiaoyao Zheng, Yonglong Luo, Zhen Ni, Xiangnan Zhong 40.Dergi/Konferans: IEEE Transactions on Neural Networks and Learning Systems 40, 41.Amaç & Katkı: MF tabanlı sistemlerin doğrusal kısıtlarını aşmak ve veri seyrekliğini (sparsity) yüksek boyutlu uzaylarda (kernel mapping) çözümleyerek performansı iyileştirmek 42, 43.Kullanılan Algoritmalar/Yöntemler: K-DNNMF (Kernelized Deep Neural Network MF), Otokodlayıcılar (Autoencoders), MLP, KernelNet, ReLU 43, 44.Bilinmesi Gereken Anahtar Kelimeler: Matrix factorization, Kernelized Deep Learning, Neural Networks 40.Veri Seti(leri): Flixster ve MovieLens 41.Yenilik / Ne Sunuyor?: Önce Otokodlayıcı (Autoencoder) ile gizli kuralları bulur, Kernel katmanıyla yüksek boyutlu uzaya çeker ve en son Çok Katmanlı Algılayıcı (MLP) kullanarak explicit (açık) ve implicit (örtük) veriyi birleştirir 43, 45.Karşılaştırma Yöntemleri: PMF, SVD++, U-CFN, I-CFN, IGMC, GNN-SOR 41.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): RMSE ve MAE kullanılmış; SVD++ ve PMF gibi standart modellere kıyasla hem hata ciddi derecede düşmüş hem de daha hızlı ve stabil bir yakınsama elde edilmiştir 41, 46.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Saf MF algoritmalarının doğrusal handikaplarını göstererek, modelinizin (meta-sezgisel destekli MF) tahmin fonksiyonlarının neden klasik MF'ten daha üstün olacağının teorik gerekçesini sunar.Cold Start ele alınmış mı?: Evet, "Kernelized Layer" ın temel tasarlanma amacı açıkça "veri seyrekliğinin (data sparsity)" etkisini azaltmaktır 43.
Makale 23Makale Adı & Yıl: Meta-Heuristic Algorithms for Learning Path Recommender at MOOC (2021) 47.Yazar(lar): N. T. Son ve diğerleri 48.Dergi/Konferans: IEEE Access 48.Amaç & Katkı: MOOC (Çevrimiçi Açık Kurslar) sistemlerinde öğrencilere ders planı tavsiye ederken; "öğrenme hedefleri, efor ve süre" gibi çoklu faktörleri optimize etmek 47, 49.Kullanılan Algoritmalar/Yöntemler: Genetik Algoritma (GA), Karınca Kolonisi Optimizasyonu (ACO), Paralel Arama, Breadth First Search (BFS) 47, 50, 51, 49.Bilinmesi Gereken Anahtar Kelimeler: Meta-Heuristic Algorithms, Learning Path Recommender, Genetic Algorithm, Ant Colony 47, 50, 49.Veri Seti(leri): 169'dan fazla çevrimiçi kurs için "crawled" (internetten kazınmış) özel eğitim verisi 52.Yenilik / Ne Sunuyor?: Tavsiye sistemini, doğrudan bir ağ (graph) ve "Makespan (Kritik Yol/Süre) / Efor" hesaplama problemi olarak formülize eder ve Paralel ACO / GA ile çok amaçlı (multi-objective) çözüm sunar 47, 53, 54.Karşılaştırma Yöntemleri: Genetik Algoritma (GA) vs. Ant Colony (ACO) vs. Brute Force (Kapsamlı arama) 49.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Hedef Değeri (Objective Value/Fitness) ve İşlem Süresi (Saniye) cinsinden karşılaştırılmıştır. ACO kritik yolu daha iyi bulurken, GA daha hızlı ve stabil sonuç vermiştir 55, 49.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Doğrudan popülasyon tabanlı meta-sezgisellerin (GA ve Karınca Kolonisi), bir tavsiye sisteminin matrislerinde sadece hata küçültmek için değil, yolları veya eforları (işlem maliyeti) küçültmek için de nasıl yapılandırılacağını (özellikle paralel işleme 53, 54) gösterir.Cold Start ele alınmış mı?: Eğitim rotası (makespan) ve maliyet optimizasyonu hedeflendiği için net bir biçimde "Cold-Start" kavramından bahsedilmemiştir 47, 55.

Makale 24Makale Adı & Yıl: Recommender Systems Based on Nonnegative Matrix Factorization: A Survey (2025) 1.Yazar(lar): Sajad Ahmadian, Kamal Berahmand, Mehrdad Rostami, Saman Forouzandeh, Parham Moradi, Mahdi Jalili 2.Dergi/Konferans: IEEE Transactions on Artificial Intelligence 1.Amaç & Katkı: Tavsiye sistemlerinde negatif olmayan matris çarpanlarına ayırma (NMF) yöntemlerinin kullanımını; kısıtlı, yapısal ve derin öğrenme entegreli modeller üzerinden kapsamlı bir şekilde incelemek 1.Kullanılan Algoritmalar/Yöntemler: Negatif Olmayan Matris Çarpanlarına Ayırma (NMF), Sparse NMF (SNMF), Graph Regularized NMF, Deep NMF, Orthogonal NMF 3-6.Bilinmesi Gereken Anahtar Kelimeler: Collaborative filtering, Matrix factorization, Nonnegative matrix factorization, Recommender systems 7.Veri Seti(leri): MovieLens (100K, 1M, 10M, 25M), Planet-Lab, Brightkite, CiaoDVD, Epinions, Netflix, vb. 8, 9.Yenilik / Ne Sunuyor?: Model tabanlı işbirlikçi filtreleme yaklaşımları için yeni bir taksonomi sunar ve NMF modellerinin veri seyrekliği, ölçeklenebilirlik gibi zorluklarla nasıl başa çıktığını sistematize eder 10.Karşılaştırma Yöntemleri: Farklı NMF varyantlarının (SNMF, GNMF, ONMF, RNMF, NMTF, WNMF, BNMF, TNMF, DNMF, INMF) literatürdeki performans karşılaştırması 11.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE, RMSE, Precision, Recall, F1 skorları; örneğin GTS-NTD modeli MovieLens 100K'da en iyi MAE (0.2897) ve RMSE (0.3605) değerlerine ulaşmıştır 12, 13.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Kendi MF modelinize eklenebilecek "seyreklik (sparsity)" veya "graf düzenlileştirme" kısıtlamalarını netleştirir; meta-sezgisel algoritmanızı, bu NMF kısıtlarını optimize etmek için kurgulayabilirsiniz.Cold Start ele alınmış mı?: Evet, yan bilgi (side information) ve bağlamsal bilgilerin entegrasyonu sayesinde soğuk başlangıç (cold start) sorununun hafifletildiği vurgulanmıştır 14, 15.
Makale 25Makale Adı & Yıl: Comprehensive Evaluation of Matrix Factorization Models for Collaborative Filtering Recommender Systems (2024) 16.Yazar(lar): Jesús Bobadilla, Jorge Dueñas-Lerín, Fernando Ortega, Abraham Gutiérrez 16.Dergi/Konferans: arXiv / ETSISI, Technical University of Madrid 16.Amaç & Katkı: İşbirlikçi filtreleme tabanlı tavsiye sistemlerinde kullanılan altı farklı Matris Çarpanlarına Ayırma (MF) modelini sadece doğruluk değil, aynı zamanda yenilik (novelty) ve çeşitlilik (diversity) açısından da değerlendirmek 16, 17.Kullanılan Algoritmalar/Yöntemler: PMF, BiasedMF, NMF, BeMF (Bernoulli MF), BNMF (Bayesian Non-negative MF), URP (User Ratings Profile) 18.Bilinmesi Gereken Anahtar Kelimeler: Matrix factorization, Collaborative filtering, Recommender Systems, Novelty, Diversity 16, 19.Veri Seti(leri): MovieLens (100K, 1M), FilmTrust, MyAnimeList 17.Yenilik / Ne Sunuyor?: Modellerin salt hata oranlarının ötesine geçerek, hangi MF algoritmasının hangi senaryoda (örn. yenilikçi tavsiye, gruplara tavsiye veya şeffaflık) daha başarılı olduğuna dair deneysel bir rehber sunar 16, 20.Karşılaştırma Yöntemleri: Belirtilen 6 MF modeli (PMF, BiasedMF, vb.) birbirleriyle karşılaştırılmıştır 18.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): MAE, Precision, Recall, NDCG, Novelty, Diversity. BiasedMF ve PMF tahminde en iyi sonucu verirken, NMF modelinin yenilik ve çeşitlilikte öne çıktığı kanıtlanmıştır 21-23.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF altyapınızın tabanını seçerken size yön gösterir. Tasarlayacağınız meta-sezgisel sadece hata (MAE/RMSE) düşürmeyi değil, çeşitliliği (diversity) artırmayı da hedef fonksiyonu olarak alabilir.Cold Start ele alınmış mı?: Evet, özellikle PMF'in uyarlanabilir (adaptive) öncüller kullanarak soğuk başlangıç yapan kullanıcılara (cold-start users) isabetli öneriler sunabildiği belirtilmiştir 18.
Makale 26Makale Adı & Yıl: Neural Matrix Factorization Recommendation for User Preference (2022) 24.Yazar(lar): Huazhen Liu vd. 24.Dergi/Konferans: Computational Intelligence and Neuroscience 24.Amaç & Katkı: Geleneksel MF'in doğrusal sınırlarını aşmak için açık (explicit) ve örtük (implicit) geri bildirimleri sinir ağları ile birleştirerek kullanıcı tercihlerini daha isabetli tahmin etmek 25.Kullanılan Algoritmalar/Yöntemler: Neural Matrix Factorization (EINMF), Multilayer Perceptron (MLP), Matris Çarpanlarına Ayırma 26.Bilinmesi Gereken Anahtar Kelimeler: Neural matrix factorization, Explicit-implicit feedback, User preference, Multilayer perceptron 25, 26.Veri Seti(leri): MovieLens-100k, MovieLens-1m 27.Yenilik / Ne Sunuyor?: Hem sığ (shallow) doğrusal özellikleri matris çarpanlarına ayırma ile, hem de derin doğrusal olmayan özellikleri MLP ile öğrenen ve yepyeni bir hibrit kayıp (loss) fonksiyonu kullanan EINMF modelini önerir 26, 28.Karşılaştırma Yöntemleri: NCF, DMF, Pop, ItemKNN, BPR-MF algoritmaları 27, 29.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): HR@10 (Hit Ratio) ve NDCG@10 metrikleri ile test edilmiş; EINMF modeli veri büyüklüğü ve seyrekliği fark etmeksizin tüm derin öğrenme baseline modellerini geride bırakmıştır 27, 30.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF modelinizi derin öğrenme (MLP) ile güçlendirmek isterseniz mimarinizi nasıl kurgulayacağınızı gösterir. Meta-sezgiseliniz, bu sinir ağının veya MF bileşeninin hiperparametrelerinin aramasında kullanılabilir.Cold Start ele alınmış mı?: Gelecek çalışmalarda özellik verilerinin eklenmesiyle veri seyrekliği ve soğuk başlangıç (cold start) sorunlarının daha fazla hafifletileceği belirtilmiştir (doğrudan nihai odak cold start değildir) 28.
Makale 27Makale Adı & Yıl: Probabilistic Matrix Factorization Recommendation Approach for Integrating Multiple Information Sources (2023) 31.Yazar(lar): Jiangzhou Deng, Xun Ran, Yong Wang, Leo Yu Zhang, Junpeng Guo 31.Dergi/Konferans: IEEE Transactions on Systems, Man, and Cybernetics: Systems 31.Amaç & Katkı: Yalnızca puanları (ratings) değil, kullanıcı yorumlarını (reviews) ve bu puanların güvenilirliğini de PMF modeline entegre ederek tavsiye performansını artırmak 31.Kullanılan Algoritmalar/Yöntemler: Olasılıksal Matris Çarpanlarına Ayırma (PMF), Bernoulli distribution, Sentiment analysis (Duygu analizi) 31, 32.Bilinmesi Gereken Anahtar Kelimeler: Collaborative filtering, Probabilistic matrix factorization, Recommender systems, Sentiment analysis, Reliability 31.Veri Seti(leri): Dört farklı Amazon veri seti (IV, DM, AA, MT) 33.Yenilik / Ne Sunuyor?: Yorumlardan elde edilen duygu skorunu ve yorum faydalılığını (helpfulness), ikili bir güvenilirlik matrisine dönüştürerek PMF'e katan özel bir ağırlıklandırma stratejisi sunar 31.Karşılaştırma Yöntemleri: MF, PMF, SBMF+R, BeMF, NCF, NCFCM, DeepCoNN, D-ATT, MPCN, IAutoRec 32, 34.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): RMSE, PPR, F1 ve NDCG. Önerilen model (OURS) hata oranını (RMSE) düşürerek diğer tüm MF ve Derin Öğrenme tabanlı metotlara üstünlük sağlamıştır 35.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Modele farklı veri kaynakları (puan + yorum + güvenilirlik) eklerken bir "ağırlık matrisi (weight matrix)" kullanmanız gerekecektir; meta-sezgisel algoritmanız bu ağırlıkları optimum seviyede ayarlamak için kurgulanabilir.Cold Start ele alınmış mı?: Veri seyrekliği durumunda salt puanların yetersiz kaldığı vurgulanmış, yorum ve güvenilirlik verilerinin modele katılmasıyla seyrek veri (ve dolaylı yoldan cold start) sorunlarına çözüm sunulmuştur 36.
Makale 28Makale Adı & Yıl: State-of-the-Art Reviews of Meta-Heuristic Algorithms with Their Novel Proposal for Unconstrained Optimization and Applications (2021) 37.Yazar(lar): Raghav Prasad Parouha, Pooja Verma 37.Dergi/Konferans: Archives of Computational Methods in Engineering 37.Amaç & Katkı: Geleneksel meta-sezgisel algoritmaları incelemek ve Parçacık Sürü Optimizasyonu (PSO) ile Diferansiyel Gelişim (DE) algoritmalarının güçlü yönlerini birleştiren yeni bir hibrit (ihPSODE) model önermek 37.Kullanılan Algoritmalar/Yöntemler: Particle Swarm Optimization (nPSO), Differential Evolution (nDE), Hibrit ihPSODE 37-39.Bilinmesi Gereken Anahtar Kelimeler: Meta-heuristic algorithms, Unconstrained optimization, Particle swarm optimization, Differential evolution 37-39.Veri Seti(leri): 23 temel, 30 CEC 2014 ve 30 CEC 2017 kısıtsız benchmark fonksiyonu ile 3 gerçek dünya problemi 37, 40.Yenilik / Ne Sunuyor?: PSO'da doğrusal azalan eylemsizlik ağırlığı, DE'de ise yeni mutasyon stratejileri geliştirerek; her iki algoritmayı yerel optimaya düşmekten kurtaracak ve ardışık çalışacak bir hibrit mimaride birleştirir 37, 41.Karşılaştırma Yöntemleri: GSA, GWO, SSA, EO, HHO, HTS, JADE, SHADE, DEPSO gibi onlarca güncel meta-sezgisel ile karşılaştırılmıştır 42.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Fonksiyonların minimum değerleri, Ortalama (Mean), Standart Sapma (Std). ihPSODE çoğu benchmark fonksiyonunda diğer yöntemleri geride bırakarak küresel optimuma en hızlı ulaşan model olmuştur 43, 44.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF altyapınızı güçlendirmek için seçeceğiniz meta-sezgisel algoritmayı kurgularken "birden fazla meta-sezgiseli nasıl hibritlerim?" sorusuna ve optimizasyon mimarisine ışık tutan devasa bir rehberdir.Cold Start ele alınmış mı?: Doğrudan bir optimizasyon makalesi olduğu için tavsiye sistemlerindeki Cold Start problemi yer almaz, ancak algoritmanın yerel minimumda "donup kalma (stagnation)" problemi çözülmüştür 37.
Makale 29Makale Adı & Yıl: Dung beetle optimizer: a new meta-heuristic algorithm for global optimization (2023) 45.Yazar(lar): Jiankai Xue, Bo Shen 45.Dergi/Konferans: The Journal of Supercomputing 45.Amaç & Katkı: Bok böceklerinin (dung beetle) top yuvarlama, dans etme, yiyecek arama, çalma ve üreme davranışlarından esinlenerek hem küresel keşfi (exploration) hem de yerel sömürüyü (exploitation) dengeleyen yeni nesil bir meta-sezgisel algoritma geliştirmek 45.Kullanılan Algoritmalar/Yöntemler: Dung Beetle Optimizer (DBO) 45, 46.Bilinmesi Gereken Anahtar Kelimeler: Dung beetle optimizer (DBO), Meta-heuristic algorithm, Swarm intelligence, Global optimization 45, 47.Veri Seti(leri): 23 standart benchmark fonksiyonu, 29 CEC-BC-2017 test fonksiyonu ve 3 karmaşık mühendislik tasarım problemi 45, 48.Yenilik / Ne Sunuyor?: Böceklerin ışık şiddetine veya engellere göre yön değiştirme (dans) davranışlarını matematiksel olarak modeller; böylece mevcut popüler algoritmaların (PSO, GWO vb.) yerel optimuma takılma zafiyetini giderir 45, 49, 50.Karşılaştırma Yöntemleri: HHO, PSO, GWO, WOA, SSA, SCA, MVO meta-sezgisel algoritmaları 51, 52.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Ortalama (Mean), Standart Sapma (Std), Wilcoxon testleri. DBO, rakiplerine kıyasla bariz şekilde daha yüksek çözüm hassasiyetine ve daha hızlı yakınsama (convergence) hızına ulaşmıştır 48, 52, 53.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: Kendi MF'inizi optimize etmek için eski bir PSO veya GA kullanmak yerine, 2023 çıkışlı bu çok yeni ve güçlü "Dung Beetle (DBO)" meta-sezgiselini sisteminize entegre etmeniz için çok güçlü bir modern alternatiftir.Cold Start ele alınmış mı?: Optimizasyon odaklı olduğu için Cold Start kavramı geçmez; ancak arama uzayındaki kör noktalara (karanlık bölgeler) karşı dayanıklı tasarlandığı belirtilmiştir 49.
Makale 30Makale Adı & Yıl: Hybrid Matrix Factorization Based Graph Contrastive Learning for Recommendation System (Yıl metinde net değil, içerikten hareketle 2022 veya 2023) 54.Yazar(lar): Kaynaklarda net yazar künyesi geçmemiştir (GCL ve MF üzerine bir araştırma yazısı) 54.Dergi/Konferans: Belirtilmemiş.Amaç & Katkı: Küresel işbirlikçi (collaborative) bilgileri daha iyi korumak için iki farklı çarpanlarına ayırma yöntemini (MF ve SVD) kullanarak, çıkarılan özellikleri bir graf karşılaştırmalı öğrenme (Graph Contrastive Learning) modeline beslemek 54.Kullanılan Algoritmalar/Yöntemler: Matrix Factorization (MF), Singular Value Decomposition (SVD), Graph Contrastive Learning (HMFGCL) 54, 55.Bilinmesi Gereken Anahtar Kelimeler: Matrix Factorization, Singular Value Decomposition, Graph Contrastive Learning 54.Veri Seti(leri): ML-100K, LastFM-1000, ModCloth-1000 56, 57.Yenilik / Ne Sunuyor?: Geleneksel olarak tek bir MF kullanan yapıların aksine, MF ve SVD'yi hibrit (HMFGCL) bir modülde toplayıp; farklı boyutsal indirgemelerin yarattığı zıt fakat tamamlayıcı özellikleri aynı anda elde eder 54, 58.Karşılaştırma Yöntemleri: DMF, GCMC, NGCF, EASE, LightGCN, ENMF, SimpleX, SGL, SimGCL, LightGCL, DirectAU, XSimGCL 57.Performans Metrikleri ve Sonuçlar (MAE, RMSE vb.): Recall@10/20 ve NDCG@10/20. Sadece MF veya sadece SVD kullanılan versiyonlara (HMFGCL-M, HMFGCL-S) kıyasla, her iki bileşenin bir arada kullanılması performansı %7-11 oranında artırmıştır 57, 58.Kendi hibrit MF + Metaheuristic çalışmamla ilişkisi: MF ile SVD gibi başka bir boyutsal indirgeme yönteminin birlikte (hibrit) nasıl kurgulanacağını gösterir. Çıkan bu karmaşık matris sistemindeki gürültüleri yok etmek için bir meta-sezgisel arama uzayı belirleyebilirsiniz.Cold Start ele alınmış mı?: Doğrudan soğuk başlangıç yerine Graf Karşılaştırmalı Öğrenme (GCL) mimarisinin genel gürültüyü ve matris seyrekliğini (sparsity) gidererek sistemi rahatlattığı görülmektedir 59
"""

def load_source_text() -> str:
    """
    Prefer external raw text file so the Excel can be regenerated
    without editing this script.
    """
    docs_dir = Path(__file__).resolve().parents[1] / "docs"
    raw_path = docs_dir / "literature_raw.txt"
    if raw_path.exists():
        # Be tolerant to encoding issues; user may paste in various encodings.
        return raw_path.read_text(encoding="utf-8", errors="replace")
    return RAW_TEXT


def main() -> None:
    source = load_source_text()
    articles = split_articles(source)
    if not articles:
        raise SystemExit("No articles found in RAW_TEXT.")

    rows: list[dict[str, str]] = []
    for n, block in sorted(articles, key=lambda x: x[0]):
        row = parse_block(block)
        row["_Makale No"] = n
        rows.append(row)

    df = pd.DataFrame(rows)
    df = df.sort_values("_Makale No").drop(columns=["_Makale No"])
    df = df.reindex(columns=COLUMNS)

    # --- Özel makale adı sıralaması (senin verdiğin listeye göre) ---
    custom_order = [
        "Analysis of Movie Intelligent Recommendation Algorithm based on MovieLens Platform",
        "Movie Recommendation Systems: Advanced Techniques for Personalized Content Suggestion",
        "Combining Cmab with Matrix Factorization and Clustering For Enhanced Movie Recommendations",
        "An Efficient Hybrid Parallel SGD Algorithm for Matrix Factorization in Recommendation Systems",
        "Hybrid Matrix Factorization Based Graph Contrastive Learning for Recommendation System",
        "Multi‑criteria recommendation system based on deep matrix factorization and regression techniques",
        "Implementation and Effectiveness Evaluation of Four Common Algorithms of Recommendation Systems: User Collaboration Filter, Item based Collaborative Filtering, Matrix Factorization and Neural Collaborative Filtering",
        "Neural Matrix Factorization Recommendation for User Preference",
        "Probabilistic Matrix Factorization Recommendation Approach for Integrating Multiple Information Sources",
        "TopC-CAMF: A Top Context Based Matrix Factorization Recommender System",
        "GAN-based Matrix Factorization for Recommender Systems",
        "Kernelized Deep Learning for Matrix Factorization",
        "Comprehensive Evaluation of Matrix Factorization Models for Collaborative Filtering Recommender Systems",
        "Matrix Factorization Recommendation Algorithm Based on Attention Interaction",
        "Recommender Systems Based on Nonnegative Matrix Factorization: A Survey",
        "IMPROVED PROBABILISTIC MATRIX FACTORIZATION MODEL FOR SPARSE DATASETS",
        "Collaborative filtering recommendation algorithm based on user correlation",
        "Sparse Matrix Factorization Algorithm for Real-Time Movie Recommendation Systems",
        "Emotion-Aware Movie Recommendation System using Hybrid Dipper-Throated and Grey Wolf Optimization with Autoencoder and Hybrid Filtering",
        "Hybrid crow search and uniform crossover algorithm-based clustering for top-N recommendation system",
        "Meta-Heuristic Algorithms for Learning Path Recommender at MOOC",
        "A survey of recommender systems with multi-objective optimization",
        "Applying particle swarm optimization algorithm-based collaborative filtering recommender system considering rating and review",
        "A collaborative recommender system enhanced with particle swarm optimization technique",
        "Recommender system with grey wolf optimizer and FCM",
        "A new recommendation system using map-reduce-based tournament empowered Whale optimization algorithm",
        "A grasshopper optimization algorithm-based movie recommender system",
        "A Movie Recommender System Based on User Profile and Artificial Bee Colony Optimization",
        "Personalized E-commerce Recommendation System using Marine Predator Algorithm with Gated Recurrent Unit",
        "A recommender system with multi-objective hybrid Harris Hawk optimization for feature selection and disease diagnosis",
        "Movie recommender system with metaheuristic artificial bee",
        "Hybrid Sparrow Clustered (HSC) Algorithm for Top-N Recommendation System",
        "Proposing improved meta-heuristic algorithms for clustering",
        "State-of-the-Art Reviews of Meta-Heuristic Algorithms with Their Novel Proposal for Unconstrained Optimization and Applications",
        "Dung beetle optimizer: a new meta-heuristic algorithm for global optimization",
        # Diğer saf optimizasyon (PSO, GBO, MVO, vb.) makaleleri en sona kalabilir
    ]

    title_col = "Makale Adı & Yıl"
    order_map: dict[int, int] = {}
    current_rank = 0
    # Her bir ismi, başlık hücresinin içinde geçiyorsa o satıra sıra numarası ata.
    for name in custom_order:
        mask = df[title_col].astype(str).str.contains(name, case=False, na=False)
        idx_list = df.index[mask].tolist()
        if not idx_list:
            continue
        for idx in idx_list:
            if idx not in order_map:
                order_map[idx] = current_rank
        current_rank += 1

    # Eşleşmeyenler sona gelsin.
    default_rank = len(custom_order) + 100
    df["_custom_order"] = df.index.map(lambda i: order_map.get(i, default_rank))
    df = df.sort_values(["_custom_order", title_col]).drop(columns=["_custom_order"])

    docs_dir = Path(__file__).resolve().parents[1] / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    xlsx_path = docs_dir / "literature.xlsx"
    csv_path = docs_dir / "literature.csv"

    df.to_excel(xlsx_path, index=False)
    df.to_csv(csv_path, index=False, encoding="utf-8-sig")

    print(f"Wrote: {xlsx_path}")
    print(f"Wrote: {csv_path}")
    print(f"Rows: {len(df)}  Cols: {len(df.columns)}")


if __name__ == "__main__":
    main()

